# Generated by Django 5.2.10 on 2026-01-23 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nombre de Etiqueta"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Color (Hex)"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Etiqueta",
                "verbose_name_plural": "Etiquetas",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterField(
            model_name="lawcase",
            name="cliente_nombre",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Cliente (Texto libre)"
            ),
        ),
        migrations.CreateModel(
            name="ActuacionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre de Plantilla"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        default="Escrito", max_length=100, verbose_name="Tipo"
                    ),
                ),
                (
                    "descripcion_template",
                    models.TextField(verbose_name="Plantilla de Descripción"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Actuación",
                "verbose_name_plural": "Plantillas de Actuaciones",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="lawcase",
            name="etiquetas",
            field=models.ManyToManyField(
                blank=True,
                related_name="expedientes",
                to="api.casetag",
                verbose_name="Etiquetas",
            ),
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(max_length=200, verbose_name="Nombre Completo"),
                ),
                (
                    "dni_ruc",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="DNI/RUC"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "notas",
                    models.TextField(blank=True, verbose_name="Notas Adicionales"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nombre_completo"],
                "indexes": [
                    models.Index(
                        fields=["dni_ruc"], name="api_cliente_dni_ruc_e09a91_idx"
                    ),
                    models.Index(
                        fields=["nombre_completo"],
                        name="api_cliente_nombre__820f7e_idx",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="lawcase",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expedientes",
                to="api.cliente",
                verbose_name="Cliente",
            ),
        ),
    ]
