# Generated by Django 5.2.10 on 2026-01-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_casetag_alter_lawcase_cliente_nombre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rol",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("abogado", "Abogado"),
                    ("usuario", "Usuario"),
                ],
                default="usuario",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
