# Generated by Django 5.2.10 on 2026-02-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_user_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawcase",
            name="abogado_responsable",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Abogado(s) Responsable(s)"
            ),
        ),
    ]
