# Generated by Django 5.2.10 on 2026-02-03 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_abogado_responsable_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseactuacion",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actuaciones_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificado por",
            ),
        ),
        migrations.AddField(
            model_name="caseactuacion",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Última modificación"
            ),
        ),
        migrations.AlterField(
            model_name="lawcase",
            name="abogado_responsable",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Abogado Responsable"
            ),
        ),
    ]
