# Generated by Django 5.2.10 on 2026-02-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_actuacion_updated_at_modified_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="casealerta",
            name="tiempo_estimado_minutos",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Tiempo estimado (minutos)",
            ),
        ),
    ]
