# Generated by Django 5.2.10 on 2026-02-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alerta_tiempo_estimado"),
    ]

    operations = [
        migrations.AddField(
            model_name="casenote",
            name="resumen",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Resumen / Descripción breve"
            ),
        ),
    ]
