# Generated by Django 5.2.10 on 2026-02-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_nota_resumen"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="caseactuacion",
            index=models.Index(
                fields=["caso", "-fecha"], name="api_caseact_caso_id_47c216_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseactuacion",
            index=models.Index(
                fields=["-created_at"], name="api_caseact_created_ce6687_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casealerta",
            index=models.Index(
                fields=["caso", "fecha_vencimiento"],
                name="api_caseale_caso_id_4eb20b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="casealerta",
            index=models.Index(
                fields=["cumplida"], name="api_caseale_cumplid_67bbd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casenote",
            index=models.Index(
                fields=["caso", "-created_at"], name="api_casenot_caso_id_6f8495_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lawcase",
            index=models.Index(
                fields=["abogado_responsable"], name="api_lawcase_abogado_6b5df2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lawcase",
            index=models.Index(
                fields=["cliente"], name="api_lawcase_cliente_224e15_idx"
            ),
        ),
    ]
