# Generated by Django 5.2.10 on 2026-02-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_caseactuacion_api_caseact_caso_id_47c216_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawcase",
            name="folder_link",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Link Carpeta Digital",
            ),
        ),
    ]
