# Generated by Django 4.2 on 2026-02-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_lawcase_folder_link"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="casealerta",
            index=models.Index(
                fields=["cumplida", "fecha_vencimiento"],
                name="api_caseale_cumplid_79dd4c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lawcase",
            index=models.Index(
                fields=["created_at"], name="api_lawcase_created_b816f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lawcase",
            index=models.Index(fields=["fuero"], name="api_lawcase_fuero_7ad4e1_idx"),
        ),
    ]
