# Generated by Django 4.2 on 2026-03-15 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_usercalendarevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Crear"),
                            ("update", "Actualizar"),
                            ("delete", "Eliminar"),
                            ("toggle", "Cambiar estado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_type", models.CharField(max_length=30)),
                ("entity_id", models.PositiveIntegerField()),
                (
                    "field_changed",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="api.lawcase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="caseactivitylog",
            index=models.Index(
                fields=["caso", "-created_at"], name="api_caseact_caso_id_25ad31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseactivitylog",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="api_caseact_entity__71f12a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="caseactivitylog",
            index=models.Index(
                fields=["user", "-created_at"], name="api_caseact_user_id_5e16b7_idx"
            ),
        ),
    ]
